"""adding total games column

Revision ID: 03c7e53597ef
Revises: 64f87f6a6d71
Create Date: 2024-12-05 17:27:57.474871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c7e53597ef'
down_revision: Union[str, None] = '64f87f6a6d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('total_games', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'words', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='unique')
    op.drop_column('stats', 'total_games')
    # ### end Alembic commands ###
