"""updating user ID to UUID

Revision ID: 225690eeee91
Revises: 03c7e53597ef
Create Date: 2024-12-05 17:51:04.109987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225690eeee91'
down_revision: Union[str, None] = '03c7e53597ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stats_user_id_fkey', 'stats', type_='foreignkey')
    op.execute('ALTER TABLE users ALTER COLUMN id TYPE UUID USING id::UUID')
    op.execute('ALTER TABLE stats ALTER COLUMN user_id TYPE UUID USING user_id::UUID')
    op.create_foreign_key('stats_user_id_fkey', 'stats', 'users', ['user_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stats_user_id_fkey', 'stats', type_='foreignkey')
    op.execute('ALTER TABLE users ALTER COLUMN id TYPE VARCHAR USING id::VARCHAR')
    op.execute('ALTER TABLE stats ALTER COLUMN user_id TYPE VARCHAR USING user_id::VARCHAR')
    op.create_foreign_key('stats_user_id_fkey', 'stats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
